### ISSUE TITLE
SSL Error 

### ISSUE THREAD

**Issue by d3pr3553d** [Netflix-Skunkworks/riskquant#8]
[errorRiskQuant.txt](https://github.com/Netflix-Skunkworks/riskquant/files/4205309/errorRiskQuant.txt)

I have tried to install RiskQuant by follwing the instructions in the ReadMe. I get an SSL error every time and so do other engineers. This is a direct clone and **pip install .** nothing more.

**Comment by mdeshon** [comment]
I'm not getting the same error. The error message looks like a certificate issue at pypi.org--maybe it was intermittent, can you try again now?

**Comment by d3pr3553d** [comment]
This is the error I'm gettin:

ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/pr/gypqzb0x4cd3569k14s8xw2c0000gn/T/pip-req-build-81f_z_dj/setup.py'"'"'; __file__='"'"'/private/var/folders/pr/gypqzb0x4cd3569k14s8xw2c0000gn/T/pip-req-build-81f_z_dj/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/pr/gypqzb0x4cd3569k14s8xw2c0000gn/T/pip-req-build-81f_z_dj/pip-egg-info
         cwd: /private/var/folders/pr/gypqzb0x4cd3569k14s8xw2c0000gn/T/pip-req-build-81f_z_dj/
    Complete output (37 lines):
    WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(136, '[X509] no certificate or crl found (_ssl.c:4109)'))': /simple/setupmeta/
    WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(136, '[X509] no certificate or crl found (_ssl.c:4109)'))': /simple/setupmeta/
    WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(136, '[X509] no certificate or crl found (_ssl.c:4109)'))': /simple/setupmeta/
    WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(136, '[X509] no certificate or crl found (_ssl.c:4109)'))': /simple/setupmeta/
    WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(136, '[X509] no certificate or crl found (_ssl.c:4109)'))': /simple/setupmeta/
    ERROR: Could not find a version that satisfies the requirement setupmeta (from versions: none)
    ERROR: No matching distribution found for setupmeta
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/local/opt/python/bin/python3.7', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/pr/gypqzb0x4cd3569k14s8xw2c0000gn/T/tmpuh4g6wv5', '--quiet', 'setupmeta']' returned non-zero exit status 1.

**Comment by mdeshon** [comment]
Try

pip install --upgrade setuptools

That may fix your issue. In any case, the problem doesn't seem to be directly related to riskquant (which is installing from the local directory) but instead is happening when pip tries to fetch one of the dependencies.

The problem has something to do with your version of pip, or setuptools, or possibly something on your network intercepting SSL connections.

**Comment by snkilmartin** [comment]
If you are still having this issue, we also just merged a PR with instructions on how to run riskquant using Docker.   This might be an option that resolves your issue:

https://github.com/Netflix-Skunkworks/riskquant#using-riskquant-via-docker
